deploying curl-based update50

diff --git a/opt/cs50/bin/update50 b/opt/cs50/bin/update50
--- a/opt/cs50/bin/update50
+++ b/opt/cs50/bin/update50
@@ -1,12 +1,8 @@
 #!/bin/bash
 
-url="https://raw.githubusercontent.com/cs50/codespace/main/.devcontainer.json"
-path="/workspaces/$RepositoryName/.devcontainer.json"
+set -o pipefail
 
-remote=$(curl -s "$url")
-local=$(<"$path")
-
-# Force update for now
-#if [ "$remote" != "$local" ]; then
-    echo "$remote" > "$path"
-#fi
+# GET and execute latest update50.sh, passing in any command-line arguments
+if ! bash <(curl --fail --header "Cache-Control: no-cache" --silent --location https://code.cs50.io/update50.sh) "$@"; then
+    echo "Unable to update codespace. Try again in a few minutes!"
+fi
